### ISSUE TITLE
Support JDK 9 Modules: multi-release jar or module name

### ISSUE THREAD

**Issue by lbalmaceda** [auth0/oss-library-gradle-plugin#19]
## Feature
Add a manifest entry for automatic module name as a small improvement for use with modules and JDK9+. Or better yet, use a plugin to create a release compatible with both 8 and 9+, for example, a multi-release jar.

### Context
[From @skjolber](https://github.com/auth0/jwks-rsa-java/issues/76#issuecomment-659012498): 
The 'deterministically part' was as follows: Maven creates a module name from the artifact name, if none is declared. Which is all fine for standalone applications, but this kind of 'local context' does not work well when writing a library; the risk is that there will be collisions or unresolvable imports downstream (i.e. in the 'global context').

I do not have an example app. But you want to create an maven or gradle app which uses the module system, and import your library as a dependency. Then check that the app can not access the library classes before adding an import statement in the app module-info.

I think for a single-artifact library like this, com.auth0.jwks-rsa is fair. And perhaps this is a good time to create a global approach for all your Gradle libraries, where you create real multi-release jars, instead of Automatic-Module-Name. Just put the module-info in a seperate source directory, and find a plugin which compiles and packages it into the release. At least that is what I'm doing with my maven projects.

## References
http://branchandbound.net/blog/java/2017/12/automatic-module-name/
https://dzone.com/articles/automatic-module-name-calling-all-java-library-maintainers

### Originally reported
- https://github.com/auth0/jwks-rsa-java/issues/76
- https://github.com/auth0/java-jwt/pull/362

**Comment by evansims** [comment]
🤖 Commenting to filter for internal tooling. Please disregard.

**Comment by jimmyjames** [comment]
Closing this as it is not on our current roadmap. We will keep an eye on this issue (or raise a new one) in case anyone wants to continue the conversation.
