### ISSUE TITLE
Support OSGi Bundles

### ISSUE THREAD

**Issue by jimmyjames** [auth0/oss-library-gradle-plugin#20]
### Description

Add support for OSGI bundles for Java libraries. Cloned from https://github.com/auth0/java-jwt/pull/422

**Comment by evansims** [comment]
🤖 Commenting to filter for internal tooling. Please disregard.

**Comment by jimmyjames** [comment]
Closing this as supporting OSGi modules is not on our current roadmap. We will keep an eye on this issue (or raise a new one) in case anyone wants to continue the conversation.
